const items = [
    {
        name: "Broccoli",
        price: '221.92',
        discounted_price: '168.66',
        discount: '24%',
        imagePath: 'img/Broccoli - 1280x934.png',
    },
    {
        name: 'Cabbage',
        price: '87.68',
        discounted_price: '70',
        discount: '20%',
        imagePath: 'img/Cabbage - 1280x1162.png',
    },
    {
        name: 'Carrots',
        price: '136.99',
        discounted_price: '65',
        discount: '53%',
        imagePath: 'img/Carrots - 1280x930.png',
    },
    {
        name: 'Bitter Gourd',
        price: '90.41',
        discounted_price: '72.33',
        discount: '20%',
        imagePath: 'img/Fresh Bitter Gourd - 1280x1209.png',
    },
    {
        name: 'Cauliflower',
        price: '84.94',
        discounted_price: '67.96',
        discount: '20%',
        imagePath: 'img/Fresh Cauliflower - 1280x1138.png',
    },
    {
        name: 'Potato',
        price: '72.6',
        discounted_price: '55',
        discount: '24%',
        imagePath: 'img/Fresh Potato - 1280x909.png',
    },
    {
        name: 'Garlic',
        price: '712.33',
        discounted_price: '420',
        discount: '41%',
        imagePath: 'img/Garlic - 960x967.png',
    },
    {
        name: 'Green Beans',
        price: '93.15',
        discounted_price: '45',
        discount: '52%',
        imagePath: 'img/Green Beans - 1280x856.png',
    },
    {
        name: 'Onion',
        price: '109.59',
        discounted_price: '87.67',
        discount: '20%',
        imagePath: 'img/Onion - 1280x701.png',
    },
    {
        name: 'Tomato',
        price: '46.58',
        discounted_price: '31',
        discount: '33%',
        imagePath: 'img/Two Juicy Tomato - 1280x1150.png',
    },
]