const items = [
    {
        name: "Broccoli",
        price: '221.92',
        discounted_price: '168.66',
        discount: '24%',
        imagePath: 'img/Broccoli - 1280x934.png',
    },
    {
        name: 'Cabbage',
        price: '87.68',
        discounted_price: '70',
        discount: '20%',
        imagePath: 'img/Cabbage - 1280x1162.png',
    },
    {
        name: 'Carrots',
        price: '136.99',
        discounted_price: '65',
        discount: '53%',
        imagePath: 'img/Carrots - 1280x930.png',
    },
    {
        name: 'Bitter Gourd',
        price: '90.41',
        discounted_price: '72.33',
        discount: '20%',
        imagePath: 'img/Fresh Bitter Gourd - 1280x1209.png',
    },
    {
        name: 'Cauliflower',
        price: '84.94',
        discounted_price: '67.96',
        discount: '20%',
        imagePath: 'img/Fresh Cauliflower - 1280x1138.png',
    },
    {
        name: 'Potato',
        price: '72.6',
        discounted_price: '55',
        discount: '24%',
        imagePath: 'img/Fresh Potato - 1280x909.png',
    },
    {
        name: 'Garlic',
        price: '712.33',
        discounted_price: '420',
        discount: '41%',
        imagePath: 'img/Garlic - 960x967.png',
    },
    {
        name: 'Green Beans',
        price: '93.15',
        discounted_price: '45',
        discount: '52%',
        imagePath: 'img/Green Beans - 1280x856.png',
    },
    {
        name: 'Onion',
        price: '109.59',
        discounted_price: '87.67',
        discount: '20%',
        imagePath: 'img/Onion - 1280x701.png',
    },
    {
        name: 'Tomato',
        price: '46.58',
        discounted_price: '31',
        discount: '33%',
        imagePath: 'img/Two Juicy Tomato - 1280x1150.png',
    },
    {
        name: 'Cherries',
        price: '234',
        discounted_price: '175.5',
        discount: '25%',
        imagePath: 'img/Cherries in Bowl - 900x850.png',
    },
    {
        name: 'Dragon Fruit',
        price: '394.53',
        discounted_price: '216',
        discount: '45%',
        imagePath: 'img/Dragon Fruit - 900x551.png',
    },
    {
        name: 'Green Grapes',
        price: '153.42',
        discounted_price: '122.74',
        discount: '20%',
        imagePath: 'img/Green Grapes - 1280x1043.png',
    },
    {
        name: 'Orange',
        price: '61.65',
        discounted_price: '49.31',
        discount: '20%',
        imagePath: 'img/Orange Half - 900x691.png',
    },
    {
        name: 'Strawberry',
        price: '1178.10',
        discounted_price: '942.50',
        discount: '20%',
        imagePath: 'img/Strawberry in plate - 1280x867.png',
    },
    {
        name: 'Banana',
        price: '98.64',
        discounted_price: '58',
        discount: '41%',
        imagePath: "img/Banana's - 640x451.png",
    },
    {
        name: 'Guava',
        price: '115.07',
        discounted_price: '80',
        discount: '30%',
        imagePath: 'img/Guava - 640x488.png',
    },
    {
        name: 'Pomegranate',
        price: '257.53',
        discounted_price: '206.02',
        discount: '20%',
        imagePath: 'img/Pomegranate - 640x486.png',
    },
    {
        name: 'Mosambi',
        price: '145.66',
        discounted_price: '116.53',
        discount: '20%',
        imagePath: 'img/Mosambi - 640x426.png',
    },
]